# Generated by Django 4.2.6 on 2023-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_unique_together'),
        ('users', '0003_newuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='rated_user', to='ratings.rating'),
        ),
    ]
