# Generated by Django 4.2.6 on 2023-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_properties_area_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
