# Generated by Django 4.2.6 on 2023-10-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_properties_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='sell',
            new_name='seller',
        ),
    ]
