# Generated by Django 4.2.6 on 2023-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_properties_lat_properties_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='number_of_bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='number_of_bedrooms',
            field=models.IntegerField(null=True),
        ),
    ]
