# Generated by Django 4.2.6 on 2023-10-15 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_is_admin_alter_newuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 10, 22, 22, 832715, tzinfo=datetime.timezone.utc)),
        ),
    ]
