# Generated by Django 4.2.6 on 2023-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_properties_property'),
        ('users', '0002_alter_newuser_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='properties.property'),
        ),
    ]
