# Generated by Django 4.2.6 on 2023-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_unique_together'),
        ('users', '0004_newuser_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_user', to='ratings.rating'),
        ),
    ]
