# Generated by Django 4.2.6 on 2023-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_properties_property'),
        ('users', '0005_alter_newuser_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_properties',
            field=models.ManyToManyField(related_name='user_ads', to='properties.property'),
        ),
    ]
