# Generated by Django 4.2.6 on 2023-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyimage'),
        ('ratings', '0002_alter_rating_unique_together'),
        ('users', '0006_newuser_user_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, related_name='rated_user', to='ratings.rating'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_properties',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_ads', to='properties.property'),
        ),
    ]
