# Generated by Django 4.2.6 on 2023-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_favorites_alter_newuser_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='mobile_phone',
            field=models.IntegerField(null=True),
        ),
    ]
