# Generated by Django 4.2.6 on 2023-10-16 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 6, 35, 16, 470222, tzinfo=datetime.timezone.utc)),
        ),
    ]
