# Generated by Django 4.2.6 on 2023-10-17 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='mobile_phone',
            field=models.IntegerField(default='0109999999'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 7, 7, 7, 636064, tzinfo=datetime.timezone.utc)),
        ),
    ]
