# Generated by Django 4.2.6 on 2023-10-31 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_newuser_mobile_phone_alter_newuser_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
        migrations.AddField(
            model_name='newuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='newuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
