# Generated by Django 4.2.6 on 2023-10-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_newuser_start_date_newuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
